#!/bin/sh

###Function: Scan for every .m file in specific folder, and compile them one by one



py_fname='jenkins_test'
mat_fname='jenkins_test.m'
test_folder='test_samples'
mcc -W python:$py_fname $mat_fname -d $test_folder
