#!/bin/sh

### To install compiled python package and do unit test
##conda activate python3.7
##cd test_samples
##dir
##ls
##python3_version=`which python3`
##echo $python3_version
##env
root_path=`pwd`
##echo $root_path
cd test_samples
##python3 test_samples/setup.py install
python3 setup.py install


pip3 install $root_path/python_packages/six-1.15.0-py2.py3-none-any.whl
pip3 install $root_path/python_packages/python_dateutil-2.8.1-py2.py3-none-any.whl 
pip3 install $root_path/python_packages/pytz-2020.4-py2.py3-none-any.whl
pip3 install $root_path/python_packages/numpy-1.19.4-cp37-cp37m-macosx_10_9_x86_64.whl
pip3 install $root_path/python_packages/pandas-1.1.5-cp37-cp37m-macosx_10_9_x86_64.whl
pip3 install $root_path/python_packages/pyobjc_core-7.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
pip3 install $root_path/python_packages/pyobjc_framework_Cocoa-7.0.1-cp37-cp37m-macosx_10_9_x86_64.whl
pip3 install scipy
##pip3 install $root_path/python_packages/scipy-1.5.4-cp37-cp37m-macosx_10_9_x86_64.whl


mwpython test_add_array.py
##conda deactivate
## mwpython test_add_array_by_binaty.py

